spring.application.name=demo
<<<<<<< HEAD
=======



# MySQL Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/bookmyshowdb
spring.datasource.username=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
>>>>>>> 20efb582298689dc13c582a263c118b9fca8b5cd
